name: run-tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.11.0-dev.6+2943df016
      - run: curl -L -w "%{http_code}" -o /usr/local/bin/zigmod https://github.com/nektro/zigmod/releases/download/r83/zigmod-x86_64-linux
      - run: chmod +x /usr/local/bin/zigmod
      - run: zigmod ci
      - run: zig build test
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.11.0-dev.6+2943df016
      - run: curl -L -w "%{http_code}" -o C:\zigmod.exe https://github.com/nektro/zigmod/releases/download/r83/zigmod-x86_64-windows.exe
      - run: C:\zigmod.exe ci
      - run: dir
      - run: zig build test
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.11.0-dev.6+2943df016
      - run: curl -L -w "%{http_code}" -o /usr/local/bin/zigmod https://github.com/nektro/zigmod/releases/download/r83/zigmod-x86_64-macos
      - run: chmod +x /usr/local/bin/zigmod
      - run: zigmod ci
      - run: zig build test
